spring:
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
  jpa:
    hibernate:
       ddl-auto: validate
  liquibase:
    change-log: classpath:/db/changelog/database-changelog.xml